services:
  redis:
    image: redis:7-alpine
    container_name: codejam-redis
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: always
    networks:
      - codejam-net

  db:
    image: postgres:18
    container_name: codejam-db
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - codejam-net
    shm_size: 128mb

  piston:
    image: ghcr.io/engineer-man/piston:latest
    container_name: codejam-piston
    privileged: true
    restart: unless-stopped
    ports:
      - '2000:2000'
    volumes:
      - piston_data:/piston
    networks:
      - codejam-net

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local
  piston_data:
    driver: local

networks:
  codejam-net:
    driver: bridge
