name: codejam

services:
  redis:
    image: redis:alpine
    container_name: codejam-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - codejam-network

volumes:
  redis_data:

networks:
  codejam-network:
    driver: bridge
