services:
  app:
    build:
      context: .
      args:
        - VITE_API_URL=/
    container_name: codejam-service
    network_mode: host
    env_file: .env.prod
    environment:
      - PORT=3000
      - REDIS_HOST=10.0.2.6
      - REDIS_PORT=6379
    restart: always
